### PR TITLE
Pka macrostate analysis

### PR DESCRIPTION
**Pull request by aakankschit**
Contains updates with the correlation plots, bar plots and performance statistics for macrostate analysis.

### CODE REVIEW

**Review by davidlmobley — CHANGES_REQUESTED** [review]
Going through this, here are some notes:
- You have a bunch of hidden `.idea` files in this repo; please remove them
- Probably add `.idea` directory to the .gitignore so you don't accidentally commit it in the future
- Not sure if it's immediately clear to readers of the titration curves plots what the numbers in the legends (1.0, 2.0 etc) mean. Add a README.md in that directory that explains these are the different formal charges?
- The titration curve legends all have solid lines, but some of the lines in the figure are dashed lines; if it's an easy fix, this would be helpful to fix 
- Make sure your README.md files document critical choices which were made for analysis; for example, in computing some of the errors, you have to assume which transitions correspond to the experimental measurements. You need to explain how you do this. Also, how do you compute error statistics if a given method doesn't predict a transition, yet that transition is observed experimentally. These choices need to be documented in text, otherwise people will have to read the code to determine what happened. (You should also say what scripts do this, and where outputs of these go.)
- I'm noticing a `popular_transitions_pKa...` file but nothing which says what it means. 

Additionally, we don't really do anything with the `microstate_analysis` directory, it seems; should we just remove it to avoid distracting the user? I think the relevant stuff is in the titration curves... Or are you planning more on this? If not we should remove.

**Comment by aakankschit** [comment]
> @davidlmobley th dashed lines in the titration curves indicate microstates while the solid lines indicate the macrostate curves. Can you further elaborate on your comment for removing the dashed lines?

**Comment by aakankschit** [comment]
@davidlmobley I added additional readme files for clarification on plots and data. Please let me know if this works

**Review by davidlmobley — APPROVED** [review]
Looks good.

**Pull request merged**
